version: "3.8"

services:
  app1:
    image: ayush2912/demo-app:latest
    ports:
      - "3001:3000"
    deploy:

      restart_policy:
        condition: on-failure
  app2:
    image: ayush2912/demo-app:latest
    ports:
      - "3002:3000"
    deploy:

      restart_policy:
        condition: on-failure

  app3:
    image: ayush2912/demo-app:latest
    ports:
      - "3003:3000"
    deploy:

      restart_policy:
        condition: on-failure
